name: xcat_test
on:
  pull_request
jobs:
  xcat_pr_test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get install -y fakeroot reprepro devscripts debhelper libcapture-tiny-perl libjson-perl libsoap-lite-perl libdbi-perl libcgi-pm-perl quilt openssh-server dpkg looptools genometools software-properties-common
      - run: echo "$GITHUB_WORKSPACE/opt/xcat/bin:$GITHUB_WORKSPACE/opt/xcat/sbin" >> $GITHUB_PATH
      - run: echo "/opt/xcat/bin:/opt/xcat/sbin" >> $GITHUB_PATH
      - run: perl github_action_xcat_test.pl
